language: python
python:
  - "2.7"
services:
  - mongodb # will start mongodb
  - rabbitmq # will start rabbitmq-server
install:
  - pip install pep8 --use-mirrors
  - pip install python-coveralls --use-mirrors
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - pip install -r requirements.txt --use-mirrors
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225,E261,W191,E101,E124 ."
  - pyflakes -x W .
script:
  - coverage run manage.py test exchange event_sourcing
after_success:
  - coveralls

